# Generated by Django 4.2.5 on 2024-01-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("verification_code", models.CharField(max_length=6)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
